language: cpp
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - libsqlite3-dev
    - libcurl4-openssl-dev
    - libxml2-dev
    - libstfl-dev
    - libjson-c-dev
    - libncursesw5-dev
    - asciidoc

matrix:
  fast_finish: true
  allow_failures:
    - compiler: clang-4.0
  include:
    - compiler: gcc-4.9
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libsqlite3-dev
            - libcurl4-openssl-dev
            - libxml2-dev
            - libstfl-dev
            - libjson-c-dev
            - libncursesw5-dev
            - asciidoc
      env:
        - COMPILER=g++-4.9
        - GCOV=/usr/bin/gcov-4.9
    - compiler: gcc-5
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - GCOV=/usr/bin/gcov-5
    - compiler: gcc-6
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER=g++-6
        - GCOV=/usr/bin/gcov-6
    - compiler: clang-3.6
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - COMPILER=clang++-3.6
        - GCOV=/usr/bin/gcov
    - compiler: clang-3.7
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - COMPILER=clang++-3.7
        - GCOV=/usr/bin/gcov
    - compiler: clang-3.8
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
        - COMPILER=clang++-3.8
        - GCOV=/usr/bin/gcov
    - compiler: clang-4.0
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main"
              key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-4.0
      env:
        - COMPILER=clang++-4.0
        - GCOV=/usr/bin/gcov
    - compiler: gcc
      os: osx
      env:
        - COMPILER=g++
        - GCOV=/usr/bin/gcov
        # a2x will run xmllint on generated files, so we have to pass the path
        # to AsciiDoc's catalog files
        - XML_CATALOG_FILES=/usr/local/etc/xml/catalog
    - compiler: clang
      os: osx
      env:
        - COMPILER=clang++
        - GCOV=/usr/bin/gcov
        # a2x will run xmllint on generated files, so we have to pass the path
        # to AsciiDoc's catalog files
        - XML_CATALOG_FILES=/usr/local/etc/xml/catalog
    - addons:
        apt:
          packages:
            - i18nspector
      env:
        - CHECKS=1

install:
  - export CXX=$COMPILER
  - cd ${TRAVIS_BUILD_DIR}
  - if [ -z "$CHECKS" ]; then   ./travis-get-deps.sh   ; fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  # Compiling with optimizations enabled to get as accurate warnings as
  # possible. --keep-going is used to process the maximum number of the files
  # before failing; this will help with debugging build fails that happen on
  # platforms that the developer doesn't have access to.
  - if [ -z "$CHECKS" ]; then   CXXFLAGS="-O3" make --keep-going all test   ; fi
  - if [ -z "$CHECKS" ]; then   make distclean   ; fi
  - if [ -z "$CHECKS" ]; then   make PROFILE=1 all test   ; fi
  - if [ -z "$CHECKS" ]; then   ( cd test && ./test --order rand )   ; fi
  - if [ -n "$CHECKS" ]; then   make run-i18nspector | tee i18nspector.log && if `egrep '^(E|W):' i18nspector.log >/dev/null 2>&1` ; then false else true; fi   ; fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ -z "$CHECKS" ]; then   ./submit-to-coveralls.sh   ; fi
